### ISSUE TITLE
Keep bottom positioned popups fixed to the bottom even if the browser's bottom toolbar disappears

### ISSUE THREAD

**Issue by marklchaves** [PopupMaker/Popup-Maker#977]
## Describe the feature request

Allow popups that are fixed to the bottom to remain fixed to the bottom of the viewport on mobile even when the browser's bottom toolbar disappears (when scrolling down).

### Temporary fix

```css
@media (max-width: 640px) {
    #popmake-15.pum-container { /* Change to your popup's ID */
      bottom: 0 !important;
      margin-bottom: 0 !important;
      max-height: 500px; /* Change to your height */
      top: auto !important;
    }
  }
```

## Use case

See the OP on .org.

https://wordpress.org/support/topic/scrolling-on-mobile-6/

## Example screenshots (if any)

Screencast: https://share.wppopupmaker.com/mXuPBLZq
